### ISSUE TITLE
[Feature request] Lista de estudiantes de la asignatura

### ISSUE THREAD

**Issue by RafaelMoralesV** [exdevutem/api-mi-utem#8]
Anteriormente existía un endpoint que mostraba los estudiantes de una sección en la que el usuario estuviera inscrito. Este endpoint, según comentó Jorge en su momento, fue eliminado con el paso a SIGA, pero la pantalla quedó dentro del código de la app Mi Utem.

Deberíamos volver a integrar este endpoint y pantalla a la app?

Issue relacionada: exdevutem/mi-utem#10

**Comment by mapacheverdugo** [comment]
Se cierra ya que quedó mergeado en #11, ahora solo faltaría hacer el cambio de nuevo en la app
